### ISSUE TITLE
Sugerencias de Mejora

### ISSUE THREAD

**Issue by fernandeusto** [dgongut/docker-controller-bot#4]
1 - Variable en el docker-compose para que no ofrezca las actualizaciones de los contenedores que tenemos parados.
2 - Variable en el docker-compose para establecer una hora a la que comprobar las actualizaciones (por ejemplo cada 24h pero a las 20:00)
3 - Mientras esta descargando la nueva imagen mostrar el tamaño y el progreso: "Descargando...(652Mb - 17%)"
4 - Cuando actualizas, primero levantar la nueva imagen descargada y una vez iniciada eliminar la imagen antigua para minimizar el tiempo que esta parado el servicio. Me ha parecido que ahora los pasos son descargar la nueva, eliminar la vieja y reiniciar contenedor, deberia ser descargar, reiniciar y eliminar la antigua.

Felicidades por el proyecto

**Comment by dgongut** [comment]
¡Buenas!

Se tendrán en cuenta tus sugerencias para próximas mejoras.

En el campo de las actualizaciones queda mucho por mejorar y es donde más me estoy enfocando actualmente. Muchas gracias por el apoyo y tu interés ❤️

**Comment by rdlvm** [comment]
Es normal que en el log aparezcan tantos errores/excepciones?


2024-01-25 12:40:34,979 (__init__.py:1147 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"

2024-01-25 12:40:34,981 (__init__.py:1149 MainThread) ERROR - TeleBot: "Exception traceback:

Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 1140, in __threaded_polling

    polling_thread.raise_exceptions()

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 110, in raise_exceptions

    raise self.exception_info

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 92, in run

    task(*args, **kwargs)

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 661, in __retrieve_updates

    updates = self.get_updates(offset=(self.last_update_id + 1),

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 633, in get_updates

    json_updates = apihelper.get_updates(

                   ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 321, in get_updates

    return _make_request(token, method_url, params=payload)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 164, in _make_request

    json_result = _check_result(method_name, result)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 191, in _check_result

    raise ApiTelegramException(method_name, result, result_json)

telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

"

2024-01-25 12:41:08,337 (__init__.py:1147 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"

2024-01-25 12:41:08,339 (__init__.py:1149 MainThread) ERROR - TeleBot: "Exception traceback:

Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 1140, in __threaded_polling

    polling_thread.raise_exceptions()

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 110, in raise_exceptions

    raise self.exception_info

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 92, in run

    task(*args, **kwargs)

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 661, in __retrieve_updates

    updates = self.get_updates(offset=(self.last_update_id + 1),

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 633, in get_updates

    json_updates = apihelper.get_updates(

                   ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 321, in get_updates

    return _make_request(token, method_url, params=payload)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 164, in _make_request

    json_result = _check_result(method_name, result)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 191, in _check_result

    raise ApiTelegramException(method_name, result, result_json)

telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

"

2024-01-25 12:41:41,690 (__init__.py:1147 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"

2024-01-25 12:41:41,697 (__init__.py:1149 MainThread) ERROR - TeleBot: "Exception traceback:

Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 1140, in __threaded_polling

    polling_thread.raise_exceptions()

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 110, in raise_exceptions

    raise self.exception_info

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 92, in run

    task(*args, **kwargs)

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 661, in __retrieve_updates

    updates = self.get_updates(offset=(self.last_update_id + 1),

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 633, in get_updates

    json_updates = apihelper.get_updates(

                   ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 321, in get_updates

    return _make_request(token, method_url, params=payload)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 164, in _make_request

    json_result = _check_result(method_name, result)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 191, in _check_result

    raise ApiTelegramException(method_name, result, result_json)

telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

"

2024-01-25 12:42:15,041 (__init__.py:1147 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"

2024-01-25 12:42:15,044 (__init__.py:1149 MainThread) ERROR - TeleBot: "Exception traceback:

Traceback (most recent call last):

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 1140, in __threaded_polling

    polling_thread.raise_exceptions()

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 110, in raise_exceptions

    raise self.exception_info

  File "/usr/lib/python3.11/site-packages/telebot/util.py", line 92, in run

    task(*args, **kwargs)

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 661, in __retrieve_updates

    updates = self.get_updates(offset=(self.last_update_id + 1),

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/__init__.py", line 633, in get_updates

    json_updates = apihelper.get_updates(

                   ^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 321, in get_updates

    return _make_request(token, method_url, params=payload)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 164, in _make_request

    json_result = _check_result(method_name, result)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 191, in _check_result

    raise ApiTelegramException(method_name, result, result_json)

telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

"

**Comment by dgongut** [comment]
@rdlvm Buenas. Para nada es normal. Lo que esta indicandote tooodo el rato es que hay un conflicto de que 2 programas estan consultando el mismo bot. Asegurate de crear un bot en telegram para cada programa.

_make sure that only one bot instance is running_

**Comment by dgongut** [comment]
> Muchas gracias.
> 
> Tendré que mirar como usar los dos bots en uno solo, porque lo que no quería era duplicar bots y por ende chats.

Para ello hay que crear varios bots y añadirlos a un grupo (NO CANAL) como administradores (para que puedan borrar mensajes de otros usuarios, el mio al menos lo requiere).

Mi bot cuenta con la variable `TELEGRAM_GROUP` para ese caso, ya que el usuario administrador no cambia, pero el grupo donde escribe y recibe mensajes tiene un ChatID diferente al del usuario. En los logs, este bot informa desde que ChatID de grupo/conversacion esta recibiendo mensajes para que te sea mas sencillo saber que `TELEGRAM_GROUP` tienes que poner.

**Comment by rdlvm** [comment]
> ChatID

Muchísimas gracias, lo tengo funcionando como mencionas.

Buen trabajo!

**Comment by dgongut** [comment]
> 1 - Variable en el docker-compose para que no ofrezca las actualizaciones de los contenedores que tenemos parados.
> 2 - Variable en el docker-compose para establecer una hora a la que comprobar las actualizaciones (por ejemplo cada 24h pero a las 20:00) 
> 3 - Mientras esta descargando la nueva imagen mostrar el tamaño y el progreso: "Descargando...(652Mb - 17%)"
> 4 - Cuando actualizas, primero levantar la nueva imagen descargada y una vez iniciada eliminar la imagen antigua para minimizar el tiempo que esta parado el servicio. Me ha parecido que ahora los pasos son descargar la nueva, eliminar la vieja y reiniciar contenedor, deberia ser descargar, reiniciar y eliminar la antigua.
> 
> Felicidades por el proyecto

Finalmente cierro esta Issue:

1- **[Descartada]** Prefiero descartarla porque realmente sí interesa conocer que un contenedor parado tiene pendiente una actualización. No se volverá a notificar de la actualización aunque lo arranques o vuelva a buscar por lo que simplemente puedes "pasar" de esa notificación.
2- **[Descartada]** El tema de descartar esta mejora es debido a que es bastante ambigua. ¿Y si en lugar de cada 24h se pone cada hora? ¿De qué serviría en ese caso establecer una hora de actualización?
Podrías pensar bueno pues que si se elige una hora no le haga caso a las horas entre actualizaciones; el problema es que tendrían que convivir 2 metodologías de programación de chequeo de actualizaciones lo que lo hace extremadamente complejo y puede dar lugar a situaciones indeseadas.
3- **[Se valorará]**
4- **[Descartada]** Actualmente se realiza de la manera más segura posible minimizando el tiempo con el contenedor parado:

1. Se descarga la nueva imagen
2. Para el contenedor si está corriendo
3. Trata de crear el nuevo contenedor con la imagen descargada y el apellido __update-DCB_ (DCB: Docker-Controller-Bot)
4. Si se crea correctamente: Elimina el contenedor antiguo, elimina la imagen y renombre el nuevo contenedor quitándole lo de _update-DCB
5. Si no se crea correctamente: Arranca el contenedor antiguo ya que todavía no lo habíamos eliminado


¡Gracias por tus sugerencias!
